[package]
name = "event_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
event = {path = "../event" } 
ic-cdk = "0.3"
ic-cdk-macros = "0.3"